services:
  - type: web
    name: dgist-lms-autosaver
    runtime: docker
    repo: https://github.com/jykim5215/dgist-lms-autosaver
    branch: main
    plan: free
    region: singapore
    autoDeployTrigger: commit
    healthCheckPath: /healthz
    dockerfilePath: ./Dockerfile
    envVars:
      - key: AUTOSAVER_ROOT
        value: "/tmp/autosaver"
      - key: AUTOSAVER_MULTI_USER
        value: "1"
      - key: AUTOSAVER_UI_HOST
        value: "0.0.0.0"
      - key: AUTOSAVER_OPEN_BROWSER
        value: "0"
      - key: AUTOSAVER_HEADLESS
        value: "1"
      - key: AUTOSAVER_USERS_ROOT
        value: "/tmp/autosaver/users"
