#!/usr/bin/env bash
set -euo pipefail

export AUTOSAVER_UI_HOST="${AUTOSAVER_UI_HOST:-0.0.0.0}"
export AUTOSAVER_UI_PORT="${AUTOSAVER_UI_PORT:-8765}"
export AUTOSAVER_MULTI_USER="${AUTOSAVER_MULTI_USER:-1}"
export AUTOSAVER_OPEN_BROWSER="${AUTOSAVER_OPEN_BROWSER:-0}"
export AUTOSAVER_ROOT="${AUTOSAVER_ROOT:-$HOME/.lms-autosaver}"
export AUTOSAVER_HEADLESS="${AUTOSAVER_HEADLESS:-1}"

mkdir -p "$AUTOSAVER_ROOT"

python web_ui.py
